Vagrant.configure("2") do |config|

  ##############
  ##    API Server VM
  ##############
  config.vm.define :api do |api_config|

    # Box is based on Ubunty Trusty 64-bit
    api_config.vm.box = "ubuntu/trusty64"

    # Box's IP address on the network
    api_config.vm.network "private_network", ip: "192.168.13.10"

    # Open up Ports
    api_config.vm.network :forwarded_port, host: 1337, guest: 1337  # SailsJS
    api_config.vm.network :forwarded_port, host: 5858, guest: 5858  # Node-inspector
    api_config.vm.network :forwarded_port, host: 8080, guest: 8080  # Node-inspector

    # Use password loggin for VM instead private key pair
    api_config.ssh.username = 'vagrant'
    api_config.ssh.password = 'vagrant'
    api_config.ssh.insert_key = 'true'

    # Configure the VM with a provisioning script
    api_config.vm.provision :shell, :path => "provisioning/provisioning.sh"

  end

end
